package hu.ryan.fpprocessor.ui;

import java.awt.Dimension;

import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;

import hu.ryan.fpprocessor.data.Condition;

public class ViewConditionPanel extends javax.swing.JPanel {

	/**
	 * Creates new form ViewConditionPanel
	 */
	public ViewConditionPanel(Condition condition) {
		initComponents();
		lblNode.setText("Node: (" + 0 + "-" + (condition.getNodesSize() - 1) + ")");
		lblTimestamp.setText("Timestamp: (" + 0 + "-" + (condition.getNode(0).getTimestampsSize() - 1) + "):");
		lblName.setText("Condition Name: " + condition.getName());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

        btnGroupRender = new ButtonGroup();
        jPanel1 = new JPanel();
        btnClose = new JButton();
        jPanel2 = new JPanel();
        btnPDF = new JButton();
        btnWord = new JButton();
        jPanel5 = new JPanel();
        lblName = new JLabel();
        lblSelNode = new JLabel();
        lblSelTime = new JLabel();
        lblDepth = new JLabel();
        lblWSEL = new JLabel();
        lblVel = new JLabel();
        lblShearStress = new JLabel();
        lblImgRendered = new JLabel();
        btnExport = new JButton();
        jPanel3 = new JPanel();
        lblNode = new JLabel();
        txtFieldNode = new JTextField();
        lblTimestamp = new JLabel();
        txtFieldTime = new JTextField();
        btnShow = new JButton();
        jPanel4 = new JPanel();
        btnSelTime = new JButton();
        btnAll = new JButton();
        cbDepth = new JCheckBox();
        cbWSEL = new JCheckBox();
        cbSStress = new JCheckBox();
        cbVel = new JCheckBox();
        filler1 = new Box.Filler(new Dimension(0, 0), new Dimension(0, 0), new Dimension(32767, 0));

        setPreferredSize(new Dimension(600, 400));

        btnClose.setText("Close");

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addContainerGap())
        );

        btnPDF.setText("Export to PDF");
        btnPDF.setEnabled(false);

        btnWord.setText("Export to Word");
        btnWord.setEnabled(false);

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnWord)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPDF)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWord)
                    .addComponent(btnPDF))
                .addContainerGap())
        );

        jPanel5.setBorder(BorderFactory.createTitledBorder("Info"));

        lblName.setText("Condition Name: ");

        lblSelNode.setText("Selected Node:");

        lblSelTime.setText("Selected Timestamp:");

        lblDepth.setText("Depth: ");

        lblWSEL.setText("WSEL: ");

        lblVel.setText("Velocity: ");

        lblShearStress.setText("Shear Stress: ");

        lblImgRendered.setText("Images Rendered: ");

        btnExport.setText("Export Condition");

        GroupLayout jPanel5Layout = new GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExport))
                    .addComponent(lblDepth, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblWSEL, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSelTime, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSelNode, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblVel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(lblImgRendered)
                            .addComponent(lblName))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblShearStress, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblName)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSelNode)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSelTime)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDepth)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWSEL)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblShearStress)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVel)
                .addGap(18, 18, 18)
                .addComponent(lblImgRendered)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExport)
                .addContainerGap())
        );

        jPanel3.setBorder(BorderFactory.createTitledBorder("View Options"));

        lblNode.setText("Node ():");

        lblTimestamp.setText("Timestamp ():");

        btnShow.setText("Show Info");

        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(txtFieldTime)
                    .addComponent(txtFieldNode)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(lblNode)
                            .addComponent(lblTimestamp))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnShow, GroupLayout.PREFERRED_SIZE, 104, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNode)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFieldNode, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTimestamp)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFieldTime, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnShow)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(BorderFactory.createTitledBorder("Render"));

        btnSelTime.setText("Selected Timestamp");

        btnAll.setText("All");

        cbDepth.setSelected(true);
        cbDepth.setText("Depth");

        cbWSEL.setSelected(true);
        cbWSEL.setText("WSEL");

        cbSStress.setSelected(true);
        cbSStress.setText("Shear Stress");

        cbVel.setSelected(true);
        cbVel.setText("Velocity");

        GroupLayout jPanel4Layout = new GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(cbDepth)
                    .addComponent(cbWSEL)
                    .addComponent(cbVel)
                    .addComponent(cbSStress))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSelTime, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAll, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cbDepth)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbWSEL)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSStress)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbVel))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnSelTime)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAll)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filler1, GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(filler1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private JButton btnAll;
    private JButton btnClose;
    private JButton btnExport;
    private ButtonGroup btnGroupRender;
    private JButton btnPDF;
    private JButton btnSelTime;
    private JButton btnShow;
    private JButton btnWord;
    private JCheckBox cbDepth;
    private JCheckBox cbSStress;
    private JCheckBox cbVel;
    private JCheckBox cbWSEL;
    private Box.Filler filler1;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JPanel jPanel5;
    private JLabel lblDepth;
    private JLabel lblImgRendered;
    private JLabel lblName;
    private JLabel lblNode;
    private JLabel lblSelNode;
    private JLabel lblSelTime;
    private JLabel lblShearStress;
    private JLabel lblTimestamp;
    private JLabel lblVel;
    private JLabel lblWSEL;
    private JTextField txtFieldNode;
    private JTextField txtFieldTime;
    // End of variables declaration 

	public JButton getBtnAll() {
		return btnAll;
	}

	public JButton getBtnClose() {
		return btnClose;
	}

	public ButtonGroup getBtnGroupRender() {
		return btnGroupRender;
	}

	public JButton getBtnPDF() {
		return btnPDF;
	}

	public JButton getBtnSelTime() {
		return btnSelTime;
	}
	
	public JButton getBtnShow() {
		return btnShow;
	}

	public JButton getBtnWord() {
		return btnWord;
	}

	public JButton getBtnExport() {
		return btnExport;
	}

	public JLabel getLblDepth() {
		return lblDepth;
	}

	public JLabel getLblImgRendered() {
		return lblImgRendered;
	}

	public JLabel getLblSelNode() {
		return lblSelNode;
	}

	public JLabel getLblSelTime() {
		return lblSelTime;
	}

	public JLabel getLblShearStress() {
		return lblShearStress;
	}

	public JLabel getLblVel() {
		return lblVel;
	}

	public JLabel getLblWSEL() {
		return lblWSEL;
	}

	public JCheckBox getCbDepth() {
		return cbDepth;
	}

	public JCheckBox getCbSStress() {
		return cbSStress;
	}

	public JCheckBox getCbVel() {
		return cbVel;
	}

	public JCheckBox getCbWSEL() {
		return cbWSEL;
	}

	public JTextField getTxtFieldNode() {
		return txtFieldNode;
	}

	public JTextField getTxtFieldTime() {
		return txtFieldTime;
	}
}
